version: 2.1

jobs:
  validate-changes:
    docker:
      # pre-commit package is included since 20.10,change image to  circleci image
      - image: cimg/base:2022.01-20.04
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run pre-commit checks
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update && apt install -y shellcheck pre-commit git openssh-client
            pre-commit run --all-files

  workspace-base:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ./.circleci/build_image.sh base/Dockerfile tjusilei/workspace-base
            docker save tjusilei/workspace-base -o workspace-base.tar
          no_output_timeout: 20m
      - persist_to_workspace:
          root: .
          paths:
            - workspace-base.tar

  workspace-full:
    docker:
      - image: csweichel/dazzle:latest
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            uname -a
            docker load -i workspace-base.tar
            ./.circleci/dazzle_build_image.sh full/Dockerfile tjusilei/workspace-full workspace-full.tar
          no_output_timeout: 30m
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/dazzle/
            cp full/*.xml ~/test-results/dazzle
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/dazzle
      - persist_to_workspace:
          root: .
          paths:
            - workspace-full.tar

  workspace-full-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh full-vnc/Dockerfile tjusilei/workspace-full-vnc
            docker save tjusilei/workspace-full-vnc -o workspace-full-vnc.tar
      - persist_to_workspace:
          root: .
          paths:
            - workspace-full-vnc.tar

  mdbook:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh mdbook/Dockerfile tjusilei/mdbook
          no_output_timeout: 30m

  workspace-dotnet:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh dotnet/Dockerfile tjusilei/workspace-dotnet
          no_output_timeout: 60m

  workspace-dotnet-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full-vnc.tar
            ./.circleci/build_image.sh dotnet-vnc/Dockerfile tjusilei/workspace-dotnet-vnc
          no_output_timeout: 30m

  workspace-dotnet-lts:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh dotnet-lts/Dockerfile tjusilei/workspace-dotnet-lts
          no_output_timeout: 60m

  workspace-dotnet-lts-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full-vnc.tar
            ./.circleci/build_image.sh dotnet-lts-vnc/Dockerfile tjusilei/workspace-dotnet-lts-vnc
          no_output_timeout: 30m

  workspace-postgres:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh postgres/Dockerfile tjusilei/workspace-postgres
          no_output_timeout: 30m

  workspace-mysql:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh mysql/Dockerfile tjusilei/workspace-mysql
          no_output_timeout: 30m

  workspace-mongodb:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh mongodb/Dockerfile tjusilei/workspace-mongodb

  workspace-flutter:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh flutter/Dockerfile tjusilei/workspace-flutter

  workspace-gecko:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full-vnc.tar
            ./.circleci/build_image.sh gecko/Dockerfile tjusilei/workspace-gecko
          no_output_timeout: 60m

  workspace-wasm:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh wasm/Dockerfile tjusilei/workspace-wasm
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate-changes
      - workspace-base:
          requires:
            - validate-changes
      - workspace-full:
          requires:
            - workspace-base
      - workspace-full-vnc:
          requires:
            - workspace-full
      - mdbook:
          requires:
            - workspace-full
      - workspace-dotnet:
          requires:
            - workspace-full
      - workspace-dotnet-vnc:
          requires:
            - workspace-full-vnc
      - workspace-dotnet-lts:
          requires:
            - workspace-full
      - workspace-dotnet-lts-vnc:
          requires:
            - workspace-full-vnc
      - workspace-postgres:
          requires:
            - workspace-full
      - workspace-mysql:
          requires:
            - workspace-full
      - workspace-mongodb:
          requires:
            - workspace-full
      - workspace-flutter:
          requires:
            - workspace-full
      - workspace-gecko:
          requires:
            - workspace-full-vnc
      - workspace-wasm:
          requires:
            - workspace-full
